core.symlinks=false
core.autocrlf=true
core.fscache=true
color.diff=auto
color.status=auto
color.branch=auto
color.interactive=true
help.format=html
rebase.autosquash=true
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
http.sslbackend=openssl
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
credential.helper=manager
core.autocrlf=false
user.name=youhyun97
user.email=paris972006@gmail.com
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/HyeyoungCho97/Festival_2019.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
remote.upstream.url=https://github.com/MJBJ/heroku_dsfestival.git
remote.upstream.fetch=+refs/heads/*:refs/remotes/upstream/*
remote.heroku.url=https://git.heroku.com/dsfestival2019.git
remote.heroku.fetch=+refs/heads/*:refs/remotes/heroku/*
remote.origin97.url=https://github.com/youhyun97/heroku_dsfestival.git
remote.origin97.fetch=+refs/heads/*:refs/remotes/origin97/*
