# Generated by Django 2.2 on 2019-04-07 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_board_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='body',
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
