# Generated by Django 2.1.8 on 2019-04-10 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20190407_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='pwd',
            field=models.CharField(default='0000', max_length=10),
        ),
    ]
