# Generated by Django 2.2.1 on 2019-05-09 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_board_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='body',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
