# Generated by Django 2.1.8 on 2019-05-10 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_auto_20190509_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='body',
            new_name='내용',
        ),
        migrations.RenameField(
            model_name='board',
            old_name='pwd',
            new_name='비밀번호',
        ),
        migrations.RenameField(
            model_name='board',
            old_name='title',
            new_name='제목',
        ),
    ]
