# Generated by Django 2.2.1 on 2019-05-10 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_auto_20190510_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='내용',
            new_name='Text',
        ),
        migrations.RenameField(
            model_name='board',
            old_name='제목',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='board',
            old_name='비밀번호',
            new_name='pwd',
        ),
    ]
